name: Bug
description: Report a bug/issue
title: "[Bug 🐛]: "
labels: [bug]
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: what version of the software are you using that produced the error?
      placeholder: 0.1.0
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What OS are you using to run the software?
      options:
        - Linux (Default)
        - Windows
        - MacOs (arm)
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened and what did you expect?
      description: Explain in detail what happened and what was the expected behaviour? (include pictures if possible)
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
