name: Bug
description: Report a bug/issue
title: "[Bug]: "
labels: [bug]
body:
- type: input
    id: version
    attributes:
      label: Version
      description: On what version of the software are you experiencing the error?
      placeholder: 0.1.0
    validations:
      required: true
- type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: On what OS are you running the software?
      options:
        - Linux (Default)
        - Windows
        - MacOs (arm)
    validations:
      required: true
- type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true